### ISSUE TITLE
Inclusion of HT=0 in true unfolding histogram

### ISSUE THREAD

**Issue by EmyrClement** [BristolTopGroup/DailyPythonScripts#103]
Events with HT = 0 at generator level are currently being included in the true distribution for unfolding.  The plot below is a histogram of the true HT used in the response matrix.  There is a peak at HT=0, and the next non-empty bin is at HT=20GeV (as this is the threshold we apply on the gen jets for the HT calculation).

Should this first bin be included in the histogram or not?  Does it affect the unfolding in anyway? (It should be a small change either way)

![image](https://cloud.githubusercontent.com/assets/4438699/3626959/a9bc2c64-0e83-11e4-9d57-1f243f6d60e3.png)

**Comment by kreczko** [comment]
We got an answer in #171 from the ARC. Off with the <strike>head</strike> bin!
