### ISSUE TITLE
Ratio plot range in control plots

### ISSUE THREAD

**Issue by EmyrClement** [BristolTopGroup/DailyPythonScripts#189]
The range of all ratio plots for post-fit (and pre-fit) control plots is not ideal.  E.g. look at the plots in Section 5.3 Fit Results in the AN.

There should be a major tick mark at 1.0, with a tick label and a horizontal line at this value.  Currently, you would tend to look at the dotted line for 0.9 and compare the points to that.

**Comment by jjacob** [comment]
Fixed in #191.
