### ISSUE TITLE
Problems running measurements scripts on soolin

### ISSUE THREAD

**Issue by jjacob** [BristolTopGroup/DailyPythonScripts#216]
Problems with running measurements scripts on soolin:
- 01-05, 98 run fine.

The others fail:
- 99_QCD_cross_checks: https://gist.github.com/jjacob/d275e7e318e94adc6706
- x_make_fit_variable_plots: https://gist.github.com/jjacob/958afb02322344827006
- x_make_control_plots (both before fit and after normalising to fit): https://gist.github.com/jjacob/9a68a521d1c965d20d32
- x_make_binning_plots (actually runs and completes, but log file has warnings of bin numbers): https://gist.github.com/jjacob/d191e574018509bf0fbb

**Comment by kreczko** [comment]
So, problem 1 is due to
```python
l1 = axes.legend( handles, labels, numpoints = 1,
                     frameon = histogram_properties.legend_color,
                bbox_to_anchor = histogram_properties.legend_location,
                bbox_transform=plt.gcf().transFigure,
                prop = CMS.legend_properties,
                ncol = histogram_properties.legend_columns )
    l1.set_zorder(102)
```
in tools/plotting::make_control_region_comparison.

The Histogram_properties.legend_location was changed from string to tuple, but the 99 script was not changed.

**Comment by kreczko** [comment]
Problem 4 (make_binning_plots) is due to tools/ROOT_utils/get_histogram_from_file which does some "summing":
```
# change from float to double
    if root_histogram.TYPE == 'F':
        histogram = root_histogram.empty_clone(type='D')
        histogram.Add(root_histogram)
    else:
        histogram = root_histogram.Clone()
```
It creates an empty copy of the current histogram, but with a different type (float -> double).

**Comment by kreczko** [comment]
The PDF error is occurring due to 
```python
set_labels( plt, histogram_properties, show_x_label = not show_ratio, axes = axes )
```
where it is due to these two lines
```python
plt.tick_params( **CMS.axis_label_major )
plt.tick_params( **CMS.axis_label_minor )
```

More tomorrow.

**Comment by kreczko** [comment]
So it seems the problem lies with config/CMS.py
```python
axis_label_major = {
              'which':'major',
              'labelsize':40, # any value other than 40 workss
              'length':20,
              'width': 1,
              'pad': 12
              }
```
Maybe that's the reason it works on my machine but not on soolin. There is going something weird with '40' on soolin. 
Changed it to 41 (nobody will notice), let's see how that works.
